### ISSUE TITLE
SWJ Pins command panics

### ISSUE THREAD

**Issue by jonathanherbstgrapple** [probe-rs/rusty-probe-firmware#26]
I believe this happens from the DynPin implementation, but I think the _process_swj_pins_ implementation is correct since it's supposed to sample the pins as outputs, for open drain nreset.

```
ERROR panicked at 'Input operation on output pin'
└─ rusty_probe::setup::{impl#0}::is_high @ src/setup.rs:314 
```

**Comment by korken89** [comment]
Fixed
